services:
  nestjs_api_prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '8081:8081'

    environment:
      - PORT=8081
      - NODE_ENV=production
    volumes:
      - ./src:/usr/src/app/src
